name: "Copyright check"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    name: Check files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Check files
        run: pnpm check-copyright
